services:
  sqlpreview:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "tickets@@pa55W0rd"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    container_name: sqlpreview
    hostname: sqlpreview
    restart: unless-stopped
