# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to Production 

on:
  workflow_run:
    workflows: ["Deployment Workflow"]
    types:
        - manual
    branches:
        - master

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Development Workflow for Prodcution
      uses: actions/checkout@v2
      with: 
        ref: master
        repository: samkirigha/devops
        path: ./github/workflows/
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Set environment variable
      run: echo "environment=prodcution" >> $GITHUB_ENV

    - name: Run Deployment Workflow
      uses: ././github/workflows/deploy.yml
      with:
        environment: production

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ticketsservice

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./ticketsservice

    - name: Set up docker
      uses: docker/setup-buildx-action@v1
      with:
        dockerfile: ./ticketsservice/Dockerfile