name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Deployment Workflow"]
    types:
      - manual
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Deployment Workflow for Staging
      uses: actions/checkout@v2
      with:
        ref: master
        repository: samkirigha/devops
        path: .github/workflows
        # token: ${{secrets.GITHUB_TOKEN}}

    - name: Set environment variable
      run: echo "environment=staging"

    - name: Run Development Workflow
      uses: ./.github/workflows/deploy.yml
      with:
        environment: staging
